apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: petname
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nagyv/crossplane-contrib-provider-terraform-issues-79.git//tf/module?ref=main
    varFiles:
      - source: ConfigMapKey
        configMapKeyRef:
          namespace: default
          name: petname
          key: name_length
        format: JSON
  providerConfigRef:
    name: terraform-provider-github
  writeConnectionSecretToRef:
    namespace: default
    name: petname
